### ISSUE TITLE
The question about img encoder

### ISSUE THREAD

**Issue by shipengai** [Yuliang-Liu/Monkey#10]
why the whole resized img isn't used lora?

**Comment by shipengai** [comment]
what is the result if use  only one lora for the four same encoders?

**Comment by MelosY** [comment]
For the first question, the image encoder is well-trained for the resized image, so using another LoRA on it may be unnecessary. We will consider your suggestion. 

> why the whole resized img isn't used lora?

**Comment by MelosY** [comment]
> what is the result if use only one lora for the four same encoders?

In our paper, we have conducted several experiments to verify its effectiveness. You can find more details in Sec 4.1.

**Comment by shipengai** [comment]
@MelosY Thanks for your reply。Is there results on mme or mmbench?

**Comment by MelosY** [comment]
Our model does not train for instruction following ability, we have only measured the results of the MME, which you can find in the radar map.
