### ISSUE TITLE
全参数微调需要多少显存？

### ISSUE THREAD

**Issue by w-qhai** [Yuliang-Liu/Monkey#104]
我用4*A800(80g),只能设置batchsize=1，这正常吗？
正常微调需要几张？batchsize为多少？

**Comment by JeffRody** [comment]
我也是训练的时候也是显存占用过高，训练代码需要优化
![image](https://github.com/Yuliang-Liu/Monkey/assets/72346103/817058d2-b497-472b-b639-4e044935beaa)

**Comment by echo840** [comment]
您好，我们是在80g  a800上面微调的，bs设置为1。
