### ISSUE TITLE
AttributeError: 'Linear' object has no attribute 'bias'

### ISSUE THREAD

**Issue by JeffRody** [Yuliang-Liu/Monkey#105]
self.dropout, self.out_proj.weight, self.out_proj.bias,
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Linear' object has no attribute 'bias'

**Comment by echo840** [comment]
Hello, we didn't encounter this issue while running [this script](https://github.com/Yuliang-Liu/Monkey/blob/main/finetune/finetune_ds_debug.sh) on an 80GB A800. Have you experienced this error during inference?
