### ISSUE TITLE
Code of Resampler is not used in Monkey?

### ISSUE THREAD

**Issue by cpystan** [Yuliang-Liu/Monkey#110]
You have done a great work. And I have a few questions.
In your figure of Monkey, the embeddings are processed with Resampler before feeding to the Qwen-VL.
But when I run the code, I find no resample code in Monkey.
In modeling_monkey.py, line 80, image features are directly given to the Qwen-VL.
I would be so grateful if you could give me some guidance.

**Comment by echo840** [comment]
![image](https://github.com/user-attachments/assets/26f7d0f2-6843-49af-8ec2-955fc3f04ce8)
Hello, resampler is defined here.

**Comment by cpystan** [comment]
Thank you!
I noticed that the sequence length is 8192.
Is it possible to shorten the length so that I could enlarge the batch size, boosting the training?

**Comment by echo840** [comment]
I feel like this isn't working out.
