### ISSUE TITLE
使用textmonkey的脚本，进行一阶段训练，loss为0

### ISSUE THREAD

**Issue by bill4689** [Yuliang-Liu/Monkey#111]
您好，使用您开源的和数据在A800上进行一阶段训练时，在更新一个step后，会发生loss为0的情况，我使用如下脚本参数，方便问一下改如何解决吗？您使用的cuda版本是多少呢？感谢
![image](https://github.com/user-attachments/assets/3be9feba-7b8b-4ffb-b342-bcf4cfdb72f2)

**Comment by MelosY** [comment]
这个很大概率是中间的过程中出现了NaN的值，建议检查一下transformers的版本以及deepspeed的版本，我这边是4.32.0以及0.11.1。
