### ISSUE TITLE
Mini-Monkey的训练数据

### ISSUE THREAD

**Issue by xushilin1** [Yuliang-Liu/Monkey#112]
是否可以说明训练过程，即训练使用的数据和参数配置

**Comment by mxin262** [comment]
Hi~, 训练数据用的是InternVL 1.2的数据，训练代码正在内部测试复现中，很快就会在这个代码库开放

**Comment by tgyy1995** [comment]
请教下 训练用了多长时间啊

**Comment by nemonameless** [comment]
请问训练数据就是 internvl的finetune的数据集里去掉sharegpt4v吗，共只有500k去训？
sharegpt4v加上的话是对ocr问答类任务效果不好吗？
谢谢。

**Comment by mxin262** [comment]
It cost about one day using eight RTX 3090.

**Comment by mxin262** [comment]
In our experiments, using sharegpt4v resulted in a performance degradation on the text-related benchmarks.

**Comment by nemonameless** [comment]
--model_name_or_path "internvl_v2" 就是写官方的InternVL2-2B权重吧？
以及这个sft训练为什么是要freeze_mlp的？
此外infer好像还有bug，未定义target_aspect_ratio，https://github.com/Yuliang-Liu/Monkey/blob/main/project/mini_monkey/internvl/model/internvl_chat/modeling_minimonkey_chat.py#L391

**Comment by mxin262** [comment]
The internvl_v2 represents the weight of InternVL2-2B. According to our experiments, freezing MLP doesn't make much difference. Thanks for the feedback. I fix the bug and provide a inference code [here](https://github.com/Yuliang-Liu/Monkey/blob/main/project/mini_monkey/demo.py)
