### ISSUE TITLE
请问你minimonkey论文中KIE数据集这些指标是怎么测的呀？

### ISSUE THREAD

**Issue by luyao-cv** [Yuliang-Liu/Monkey#116]
![image](https://github.com/user-attachments/assets/2b307c05-aa84-4eb0-806c-79abf8181089)
请问用你的评估脚本可以测这些所有模型的KIE指标吗？

**Comment by mxin262** [comment]
You can try the [MultimodalOCR](https://github.com/Yuliang-Liu/MultimodalOCR) to evaluate the KIE.

**Comment by luyao-cv** [comment]
谢谢，已解决了。
