### ISSUE TITLE
评估结果

### ISSUE THREAD

**Issue by luyao-cv** [Yuliang-Liu/Monkey#117]
![image](https://github.com/user-attachments/assets/cf9e502a-67e0-4720-ad7a-f8dd5ed933ce)

请问最后一行的评估分数，是用这个工具测出来的吗？ [VLMEvalKit](https://github.com/open-compass/VLMEvalKit)

**Comment by mxin262** [comment]
Yes. We the [VLMEvalKit](https://github.com/open-compass/VLMEvalKit) to evaluate the results except for the ones that need to upload websites for evaluation.
