### ISSUE TITLE
mini monkey 评估ocrbench指标和论文对不上

### ISSUE THREAD

**Issue by luyao-cv** [Yuliang-Liu/Monkey#122]
您好，我用的VLMEvalKit工具，权重是Mini-Monkey-2B，结构用的intervl-2B。测试结果是：
{
    "Text Recognition": 246,
    "Scene Text-centric VQA": 169,
    "Doc-oriented VQA": 133,
    "Key Information Extraction": 167,
    "Handwritten Mathematical Expression Recognition": 68,
    "Final Score": 783,
    "Final Score Norm": 78.3
}
只有783分，与论文802分没有对应上，请问是哪里有问题吗？

**Comment by mxin262** [comment]
Hi~, you need to add the MSAC in the VLMEvalKit. I will release the evaluation code as soon as possible.

**Comment by luyao-cv** [comment]
好的，谢谢，请问这两天会更新eval代码吗？

**Comment by jinli-thu** [comment]
> Hi~, you need to add the MSAC in the VLMEvalKit. I will release the evaluation code as soon as possible.



> Hi~, you need to add the MSAC in the VLMEvalKit. I will release the evaluation code as soon as possible.

请问代码有实现MSAC嘛，怎么没找到呢

**Comment by jinli-thu** [comment]
> Hi~, you need to add the MSAC in the VLMEvalKit. I will release the evaluation code as soon as possible.

请问代码有实现MSAC吗？没有找到这部分的实现呢

**Comment by luyao-cv** [comment]
> VLMEvalKit

你好。ocrbench的指标我对上了，我这边跑出来是800，但是KIE的指标还是跑出来很低，请问能更新下评测代码吗？

**Comment by mxin262** [comment]
For VLMEvalKit, you can replace the VLMEvalKit/vlmeval/vlm/internvl_chat.py with this [file](https://huggingface.co/mx262/MiniMokney/blob/main/internvl_chat.py). It achieves 806 on OCRBench, 76.0 on TextVQA_VAL, and 60.2 on InfoVQA_VAL

**Comment by mxin262** [comment]
The issue has been resolved, and I close it. Please feel free to reopen it if you have any further questions.
