### ISSUE TITLE
关于MASC即插即用的疑惑

### ISSUE THREAD

**Issue by zhaop-l** [Yuliang-Liu/Monkey#125]
在论文中讲了MASC是即插即用的，所以table5是直接将MASC模块给迁移过去了吗？还是你们训练过的模型？
如果是直接迁移过去的，那mini-monkey的创新点是什么呢？
![image](https://github.com/user-attachments/assets/38d876d4-6d63-453d-b137-4ca4e644a042)
这个InternVL-2+MSAC的消融实验，是直接将MASC给结合上去使用的吗？还是你们训练过后的Mini-Monkey？

**Comment by mxin262** [comment]
Hi~, as detailed in the paper, cropping operation inevitably causes the segmentation of objects and connected areas. To address this issue, we propose a MASC. The MASC is the main contribution of Mini-Monkey. We finetune the InternVL-2 with MSAC to get the results of InternVL-2+MSAC. Thanks for the feedback. We will provide the results of using the MASC without training in the future.

**Comment by zhaop-l** [comment]
> Hi~, as detailed in the paper, cropping operation inevitably causes the segmentation of objects and connected areas. To address this issue, we propose a MASC. The MASC is the main contribution of Mini-Monkey. We finetune the InternVL-2 with MSAC to get the results of InternVL-2+MSAC. Thanks for the feedback. We will provide the results of using the MASC without training in the future.

So the InternVL2 in Table 5 is actually Mini-Monkey?

**Comment by zhaop-l** [comment]
Thanks
