### ISSUE TITLE
使用inference.py脚本推理的答案总是重复问题是怎么回事

### ISSUE THREAD

**Issue by yywangfei** [Yuliang-Liu/Monkey#127]
![image](https://github.com/user-attachments/assets/6f19c9ec-3b59-4ec6-ae06-de31c0de604a)
如上所示

**Comment by echo840** [comment]
请问您是使用Monkey模型还是Monkey-Chat模型？Monkey模型生成详细描述的prompt是这样的。
![image](https://github.com/user-attachments/assets/5da63e71-116a-48fe-a300-2cbeaa62f3ac)

为了良好的交互体验建议使用Monkey-Chat进行对话。

**Comment by yywangfei** [comment]
用的是monkey-chat模型

> 请问您是使用Monkey模型还是Monkey-Chat模型？Monkey模型生成详细描述的prompt是这样的。 ![image](https://private-user-images.githubusercontent.com/87795401/359322507-5da63e71-116a-48fe-a300-2cbeaa62f3ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjM0NTIsIm5iZiI6MTcyNDEyMzE1MiwicGF0aCI6Ii84Nzc5NTQwMS8zNTkzMjI1MDctNWRhNjNlNzEtMTE2YS00OGZlLWEzMDAtMmNiZWFhNjJmM2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDAzMDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNmJhNDFlOWMzYTE3OGM2YjkxNGNkNTU4ZWYzYjE0NDVjNWVhNDA2NjQ3NTc3NmI1MzViNTUxMjE1MzkyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IkJs20FckcNR_NhBpDNjXLWSmpx2tEt6Bci92cjYR1w)
> 
> 为了良好的交互体验建议使用Monkey-Chat进行对话。

用的是monkey-chat模型

**Comment by echo840** [comment]
您能把图片例子发出来吗。

**Comment by yywangfei** [comment]
> 您能把图片例子发出来吗。

不是非常确定下载的是monkey chat还是monkey，我该怎么看呢，模型是我手动下载下来的

**Comment by echo840** [comment]
![image](https://github.com/user-attachments/assets/0af4604d-4f34-48e9-80a8-8cec3ca3a801)

这您得确定是下载得这里得哪个模型了。[link](https://huggingface.co/echo840)

**Comment by yywangfei** [comment]
确认了一下，我下载的是monkey，这个不行吗？我试了两个prompt，一个是ocr the image，一个是发出来的那个，都是重复了问题

**Comment by echo840** [comment]
Monkey生成详细描述的prompt是Generate the detailed caption in English:，与您现在所用的prompt不同。如果希望使用任意prompt进行提问，建议使用monkey-chat。

**Comment by yywangfei** [comment]
![image](https://github.com/user-attachments/assets/29aaabe3-0408-4e6d-a869-84f100a827b3)
确实如此，谢谢。
另外do_sample默认是false，会报warning： `do_sample` is set to `False`. However, `top_k` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.改成true，warning才消失

**Comment by echo840** [comment]
嗯嗯，感谢，warning不影响。
