### ISSUE TITLE
作者您好~ 请问文中公开的文档街景方向 VQA的指标有使用 对应训练集做微调吗？

### ISSUE THREAD

**Issue by GITMrzk** [Yuliang-Liu/Monkey#13]

**Comment by MelosY** [comment]
STVQA and  ESTVQA have not been used for training. The other document datasets are mixed into the training dataset. More details can be found in our arxiv paper.

**Comment by GITMrzk** [comment]
> STVQA and ESTVQA have not been used for training. The other document datasets are mixed into the training dataset. More details can be found in our arxiv paper.

Thanks for the reply, I saw the relevant description in the v2 version of the paper.
