### ISSUE TITLE
Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory

### ISSUE THREAD

**Issue by autogyro** [Yuliang-Liu/Monkey#134]
I download the pre trained check point   by the following codes:

from transformers import AutoModelForCausalLM, AutoTokenizer
checkpoint = "echo840/Monkey"
model = AutoModelForCausalLM.from_pretrained(checkpoint, device_map='cuda', trust_remote_code=True).eval()
tokenizer = AutoTokenizer.from_pretrained(checkpoint, trust_remote_code=True)

Before that I installed requirment.txt file. 
while I run demo.py, got those:

File "E:\Monkey\demo.py", line 285, in main
    model, tokenizer = _load_model_tokenizer(args)
  File "E:\Monkey\demo.py", line 75, in _load_model_tokenizer
    model = MonkeyLMHeadModel.from_pretrained(
  File "E:\anaconda3\envs\minimonkey\lib\site-packages\transformers\modeling_utils.py", line 2650, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory E:/Monkey/monkey_model.

**Comment by echo840** [comment]
Hello. Can you check if the files were fully downloaded?

**Comment by autogyro** [comment]
I downloaded 18G with 84 files from HF， and save it by default folder: 'C:\\Users\\simon\\.cache\\huggingface\\...'
How to write the DEFAULT_CKPT_PATH ?  
DEFAULT_CKPT_PATH = 'C:\\Users\\simon\\.cache\\huggingface\\modules\\transformers_modules\\echo840'? or ?
THX

**Comment by echo840** [comment]
For example, you should find a path in this form: '{your dirpath}/.cache/huggingface/hub/models--echo840--Monkey/snapshots/6487a8909269713393337a2d743b95a25a3a611b'  or just "echo840/Monkey".
![image](https://github.com/user-attachments/assets/7a01d9fb-96c2-43d8-aee3-ff8cf1a393cc)

**Comment by autogyro** [comment]
thanks. I renamed this folder as your said.  after I run the demo.py , I got new error message as the following:
  File "E:\Monkey\monkey_model\tokenization_qwen.py", line 218, in _add_tokens
    if surface_form not in SPECIAL_TOKENS + self.IMAGE_ST:
AttributeError: 'QWenTokenizer' object has no attribute 'IMAGE_ST'
THX

**Comment by autogyro** [comment]
got answer from https://github.com/Yuliang-Liu/Monkey/issues/69
How to downlaod the check points you pretrained for mini monkey ?

**Comment by echo840** [comment]
![image](https://github.com/user-attachments/assets/5cb209f8-cee7-4820-9157-bcd1df8027c1)
Hello, you can refer to Minimonkey's readme.
