### ISSUE TITLE
LoRA finetuning script

### ISSUE THREAD

**Issue by SamithVa** [Yuliang-Liu/Monkey#137]
Hi, could you please provide the LoRA finetuning script?

**Comment by SamithVa** [comment]
您好，由于显卡的显存有限，我无法使用full-parameter 微调，因此我想使用LoRA 微调textMonkey， 请问您能提供一下LoRA 的脚本吗？这里我试试在`finetune_textmonkey.sh`加了 `use_lora`，不过有报错如图。
<img width="988" alt="image" src="https://github.com/user-attachments/assets/eda53960-0686-463d-83ae-bdb3451a2c41">

**Comment by MelosY** [comment]
We have not fine-tuned TextMonkey with LoRA; you may attempt to fine-tune with LoRA using Mini Monkey. From your error report, it is likely due to some compatibility issues with the Peft library; you can try again.

**Comment by SamithVa** [comment]
> We have not fine-tuned TextMonkey with LoRA; you may attempt to fine-tune with LoRA using Mini Monkey. From your error report, it is likely due to some compatibility issues with the Peft library,

Thanks
