### ISSUE TITLE
mini-monkey demo中 “读出所有文本”这个选项的 prompt 是什么？

### ISSUE THREAD

**Issue by Etpoem** [Yuliang-Liu/Monkey#139]
想使用 mini-monkey 来做 KIE 关键信息提取，发现官网demo中 "读出所有文本"这个选项对于文字识别的能力最好，对于遮挡或模糊的能直接输出为空，而不是瞎猜一堆文字，我是用自己的 prompt 效果都不好，想问一下 demo 中的prompt是怎样的，是否做了哪些特殊处理？

**Comment by mxin262** [comment]
Hi~,  demo 中的这个prompt为：“识别图中所有文字”

**Comment by Etpoem** [comment]
感谢

**Comment by Etpoem** [comment]
> Hi~, demo 中的这个prompt为：“识别图中所有文字”

好像并不是这个prompt, 在demo中使用“识别图中所有文字”这个prompt试了一下，同一张图的结果并不一样，效果没有demo“读出所有文本”这个选项的好

**Comment by mxin262** [comment]
demo中的设置为detailed layer的min_num=9, max_num=24，adaptive layer是min_num=3, max_num=8，prompt的话是“识别图中所有文字”
