### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Nice-Zhang66** [Yuliang-Liu/Monkey#144]
Hello author, I encountered an error while reproducing the code, I just used the link to download the json file in your readme to train and pointed to train_monkey.json with --data_path, but the error is reported as follows: "TypeError: list indices must be integers or slices, not str."
![20240925121643](https://github.com/user-attachments/assets/2d8fc461-d3b1-41ef-8324-34d07640fe15)

**Comment by echo840** [comment]
Hello, you need to replace <Your_Image_Dir_Path> with the folder where you place the images.

![image](https://github.com/user-attachments/assets/50a75ddd-25fa-4d31-a84f-82b4a6265713)

**Comment by Nice-Zhang66** [comment]
![20240925133902](https://github.com/user-attachments/assets/5170ecb8-5a77-4e69-88f7-1df3cc0bf2ed)
You can see the path in this image, I followed the format of train_monkey.json and wrote the json file with my own image and the corresponding comments, but I still get the above error when reading into the code.

**Comment by Nice-Zhang66** [comment]
很感谢您的回复，我在尝试用我自己的图片集和对应的注释对Monkey进行微调，但是按照您的train_monkey.json的格式编写了我自己的json文件，但是进行训练还是会报错 


| |
Wenbo Zhang
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 9/25/2024 12:52 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [Yuliang-Liu/Monkey] TypeError: list indices must be integers or slices, not str (Issue #144) |

Hello, you need to replace <Your_Image_Dir_Path> with the folder where you place the images.

image.png (view on web)

**Comment by echo840** [comment]
Can you use the following code to read train_monkey.json and output the value?
```
import json

path = "train_monkey.json"
with open(path,"r") as f:
    data = json.load(f)
print(data[0]['conversations'][1]['value'])
```

**Comment by Nice-Zhang66** [comment]
Following your method, I've tested it and both Train_monkey.json and my own json file output the corresponding value values.

**Comment by echo840** [comment]
Hello, I checked here, and I can output the corresponding values normally. Can you debug here to see the corresponding values and types of "user" and "assistant"?
![image](https://github.com/user-attachments/assets/2a2eb7e9-6795-4f53-b9bc-4af0038ec6a0)

![image](https://github.com/user-attachments/assets/1351e69b-e3c7-4cac-8e31-22e12a105c3a)

**Comment by Nice-Zhang66** [comment]
Thank you for your guidance, I did the output in the corresponding position and it shows different results from yours, below is the result of my output using train_mokey.json, you can see that both user and assistant output a corresponding image and comment, instead of user outputting the image information and assistant outputting the comment correspondingly as you did. I think there is something wrong with the train_monkey.json I downloaded, can you give me the latest available version of the json file and I'll try again.
![as you type_17273377882053](https://github.com/user-attachments/assets/3905aedc-2584-46b1-99f9-37c2e0fba4e6)

**Comment by echo840** [comment]
Maybe you need to check if the JSON file reading is correct here.
![image](https://github.com/user-attachments/assets/e0a7d827-e609-4836-b919-99b88a9ee250)

![image](https://github.com/user-attachments/assets/63767b9a-0618-46a5-ad80-cbdf08e882fc)

**Comment by echo840** [comment]
The format of the training JSON is like this; you can check if it is consistent.

```
 [{"id": "COCO2014/train2014/COCO_train2014_000000352807.jpg", "conversations": [{"from": "user", "value": "<img><Your_Image_Dir_Path>/COCO2014/train2014/COCO_train2014_000000352807.jpg</img> Generate the caption in English: "}, {"from": "assistant", "value": "A child's bathroom with toiletries on the counter and a decal on the toilet lid."}], "all_caption": ["A bathroom with a picture of a kid using the toilet on the toilet.", "Bathroom with toiletries surrounding the sink and toilet", "There is a cartoon character on the closed lid of the toilette.", "A bathroom with a toliet and a sink next to it.", "A child's bathroom with toiletries on the counter and a decal on the toilet lid."]}, {"id": "COCO2014/train2014/COCO_train2014_000000060458.jpg", "conversations": [{"from": "user", "value": "<img><Your_Image_Dir_Path>/COCO2014/train2014/COCO_train2014_000000060458.jpg</img> Is this bus moving or stationary? Answer: "},
{"from": "assistant", "value": "stationary"}], "question_id": 60458005}]

```

**Comment by Nice-Zhang66** [comment]
I re-downloaded the train_monkey.json file, checked the getitem code above, and it is the same, but after running it, I still get the same error as above!

**Comment by echo840** [comment]
> Maybe you need to check if the JSON file reading is correct here. ![image](https://private-user-images.githubusercontent.com/87795401/371046735-e0a7d827-e609-4836-b919-99b88a9ee250.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDExMzUsIm5iZiI6MTcyNzM0MDgzNSwicGF0aCI6Ii84Nzc5NTQwMS8zNzEwNDY3MzUtZTBhN2Q4MjctZTYwOS00ODM2LWI5MTktOTliODhhOWVlMjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA4NTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZTJkOGM4ZDM0ZTQ4YThiYjE0NTU3N2UxODNkZGZjZWVhYWQyZTZjOGE5Yjg2MGRiNDFlOGJjMWZhNDQ5NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.liddcbeEeZWvPnCvK8J3LSX963cJxNBA_Bg3sKHMbCg)
> 
> ![image](https://private-user-images.githubusercontent.com/87795401/371046589-63767b9a-0618-46a5-ad80-cbdf08e882fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDExMzUsIm5iZiI6MTcyNzM0MDgzNSwicGF0aCI6Ii84Nzc5NTQwMS8zNzEwNDY1ODktNjM3NjdiOWEtMDYxOC00NmE1LWFkODAtY2JkZjA4ZTg4MmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA4NTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNDE0MmViYjU4MmM4MmVkZDY1NzJjYzRkY2QxYWJmOTY0NDI5ZDNkMzY5MTBiMDEwZmRiNzMxM2EzNDQ2MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Zi0ej2fOR7bvwaa9fkYrQDdjtq9zWVtoE54J-LdCzHI)

@Nice-Zhang66   Could you please check if the JSON file reading is correct here.

**Comment by echo840** [comment]
Hello, in the training scripts, we set lazy_preprocess=True. Is this the same as your setting?
![image](https://github.com/user-attachments/assets/59328059-ad40-4cd6-a678-e5b7de966dc9)

![image](https://github.com/user-attachments/assets/1d3b2e39-7e20-42e4-b948-4e4abb7fbcad)


> json.load reads the file properly, but the preprocess code hasn't run here yet

**Comment by Nice-Zhang66** [comment]
Yes, it stays True unchanged. Frankly, I didn't change the code or the parameters. I see that the format of the json you posted in the first two posts is not exactly the same as the format I downloaded train_monkey.json in, you just gave more:‘’all_caption‘: [’A bathroom with a picture of a kid using the toilet on the toilet.‘,’ and ’, “question_id”: 60458005}]
’, the following screenshots show the format of train_monkey.json, and my train.json, respectively
![image](https://github.com/user-attachments/assets/e5747e69-8d28-4afc-ab21-3e2d026dc44e)

![image](https://github.com/user-attachments/assets/cdc0a564-0eed-4a65-9f00-454c99cb1913)

**Comment by echo840** [comment]
> json.load reads the file properly, but the preprocess code hasn't run here yet
If you set lazy_preprocess=True, preprocess code should run here, but you say "preprocess code hasn't run here yet". ‘’all_caption" and  "id" are not used in training.
![image](https://github.com/user-attachments/assets/6a19fb58-1879-42c8-9389-0367576fdde2)

**Comment by echo840** [comment]
Hello, if you have any further questions, please feel free to reopen the issue.
