### ISSUE TITLE
IndexError: index -1 is out of bounds for dimension 1 with size 0

### ISSUE THREAD

**Issue by corkiyao** [Yuliang-Liu/Monkey#145]
在测试data_generation时候（即想要生成数据集），出现错误
```python
(YYZYoLov5) (base) yaoyunze@amax:/home/data/yaoyunze/Monkey/data_generation$ /home/yaoyunze/anaconda3/envs/YYZYoLov5/bin/python /home/data/yaoyunze/Monkey/data_generation/blip2.py
  0%|                                                                                                                                             | 0/7 [00:00<?, ?it/s]torch.Size([1, 3, 224, 224])
/home/yaoyunze/anaconda3/envs/YYZYoLov5/lib/python3.8/site-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
  0%|                                                                                                                                             | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/data/yaoyunze/Monkey/data_generation/blip2.py", line 57, in <module>
    captions = model.generate({"image": image})
  File "/home/yaoyunze/anaconda3/envs/YYZYoLov5/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/yaoyunze/anaconda3/envs/YYZYoLov5/lib/python3.8/site-packages/lavis/models/blip2_models/blip2_opt.py", line 220, in generate
    outputs = self.opt_model.generate(
  File "/home/yaoyunze/anaconda3/envs/YYZYoLov5/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/yaoyunze/anaconda3/envs/YYZYoLov5/lib/python3.8/site-packages/transformers/generation/utils.py", line 1476, in generate
    and torch.sum(inputs_tensor[:, -1] == generation_config.pad_token_id) > 0
IndexError: index -1 is out of bounds for dimension 1 with size 0
```

**Comment by echo840** [comment]
Hello, could you refer to the link https://github.com/salesforce/LAVIS?tab=readme-ov-file#image-captioning to generate corresponding caption for single image?
![image](https://github.com/user-attachments/assets/523329f1-8f95-4665-87bf-d8f370c53492)

**Comment by corkiyao** [comment]
> Hello, could you refer to the link https://github.com/salesforce/LAVIS?tab=readme-ov-file#image-captioning to generate corresponding caption for single image? ![image](https://private-user-images.githubusercontent.com/87795401/371012256-523329f1-8f95-4665-87bf-d8f370c53492.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDQzOTgsIm5iZiI6MTcyNzM0NDA5OCwicGF0aCI6Ii84Nzc5NTQwMS8zNzEwMTIyNTYtNTIzMzI5ZjEtOGY5NS00NjY1LTg3YmYtZDhmMzcwYzUzNDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5NDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMDFhM2IzNGU3MDY5Y2YwMTQ3NzJjMTA2NWRkYmYwY2JhOTYyZDliMWE3YzcwODU3NjZhMmZlNzMyNjlkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zfIPS2Vzw2aLY2iL4V-urh_DEwKtjjNEjmsJjjlMLt8)

Thanks. It worked. Since i used the defaulf weight.
