### ISSUE TITLE
why make step b and step c in multilayer captioning generating in Monkey

### ISSUE THREAD

**Issue by happywinder** [Yuliang-Liu/Monkey#147]
step b is object detecting and step c is object segmentation ，what‘s difference in this 2 steps

**Comment by echo840** [comment]
Hello, in step b, we used the dense captioning model GRIT, which provides brief descriptions for some regions, but these regions are limited. In step c, SAM is used to obtain segmentation masks for all objects in the image, and we also remove the background of the objects. Therefore, step c can capture more comprehensive and fine-grained image information.
