### ISSUE TITLE
demo.py如何生成中文描述

### ISSUE THREAD

**Issue by WenmuZhou** [Yuliang-Liu/Monkey#15]

**Comment by ShuoZhang2003** [comment]
The Chinese description function in the open source demo is just for everyone's convenience, so we specially called the translation interface. The part that calls the api is not included in demo.py

**Comment by WenmuZhou** [comment]
tks

**Comment by eeyrw** [comment]
> The Chinese description function in the open source demo is just for everyone's convenience, so we specially called the translation interface. The part that calls the api is not included in demo.py

So the model itself is not capable of Chinese caption?

**Comment by echo840** [comment]
The Chinese caption is not as good as English. We will improve it in the next version.
