### ISSUE TITLE
请问dense_captions数据集中哪部分是CC3M里的图片

### ISSUE THREAD

**Issue by Yang-bug-star** [Yuliang-Liu/Monkey#152]

**Comment by Yang-bug-star** [comment]
数据集中的gcc表示什么意思

**Comment by Yang-bug-star** [comment]
有什么办法与原CC3M数据集图片对应吗

**Comment by echo840** [comment]
您好，我们用的CC3M数据是和llava用的数据相同，llava中提供了metadata.json，里面提供了原始描述和图片地址的对应关系。
![image](https://github.com/user-attachments/assets/02f43183-7214-4112-8a3b-dff74cf45212)

**Comment by Yang-bug-star** [comment]
请问你们的detailed caption数据是llava concept-balanced 595k的子集嘛

**Comment by echo840** [comment]
是的
