### ISSUE TITLE
模型训练参数疑问

### ISSUE THREAD

**Issue by Lyxxx1211** [Yuliang-Liu/Monkey#157]
请问我在训练视觉语言大模型的fine turn阶段的时候，设置per_device_train_batch_size为2，gradient_accumulation_steps为8，使用了8块GPU训练，在这种情况下明显比设置per_device_train_batch_size为1，gradient_accumulation_steps为16的时候的训练损失更高，也就是两种设置下batch size = gradient_accumulation_steps*per_device_train_batch_size*num_gpus = 128都是一致的，请问背后的原因是什么

**Comment by MelosY** [comment]
首先简单的梯度求和策略无法确保梯度累积与完整批量训练的数学等价性。
在大多数LLM训练中使用的交叉熵损失计算过程中，通常需要对非填充或非忽略的token数量进行归一化，确保损失值与训练序列中的有效token数量相匹配。
为简化分析，我们假设序列长度等于数据集平均长度。在实际的梯度累积过程中，各小批量的损失被独立计算后直接相加，这导致最终的总损失比完整批量训练的损失大G倍（G为梯度累积步数）。要修正这一问题，需要对每个累积的梯度进行1/G的缩放，以匹配完整批量训练的结果。然而这种缩放方法的有效性建立在小批量间序列长度一致的假设之上。

在实际训练LLM等模型时，序列长度的变化是常见现象，这种变化会导致损失计算出现偏差。在因果语言模型训练等应用场景中，正确的梯度累积方法应当首先计算累积步骤中所有批次的总体损失，随后将其除以这些批次中非填充token的总数。这与单独计算每个批次损失后取平均的方法有本质区别。

希望这个解释能解答你的疑惑。
