### ISSUE TITLE
flash_attn.flash_attention

### ISSUE THREAD

**Issue by errorrs** [Yuliang-Liu/Monkey#160]
![image](https://github.com/user-attachments/assets/6dc89c4a-4531-4cca-ab01-5581c3da094c)
ModuleNotFoundError: No module named 'flash_attn.flash_attention'

**Comment by errorrs** [comment]
I tried several versions of flash-attn,including 2.3.3 2.3.5 the problem still exists

**Comment by echo840** [comment]
![image](https://github.com/user-attachments/assets/47722c3b-4670-4acc-a4ec-97f6fc58baa5)

Hello, you can follow these steps to install Flash Attention.

**Comment by errorrs** [comment]
I have another question:how many GPU memory do I  need to run eval/eval.sh? I use two 24GB 4090 and failed

**Comment by errorrs** [comment]
> ![image](https://private-user-images.githubusercontent.com/87795401/394205712-47722c3b-4670-4acc-a4ec-97f6fc58baa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjcwMDcsIm5iZiI6MTczMzgyNjcwNywicGF0aCI6Ii84Nzc5NTQwMS8zOTQyMDU3MTItNDc3MjJjM2ItNDY3MC00YWNjLWE0ZWMtOTdmNmZjNThiYWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDEwMzE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZDVmOTBhZWVmYjE4YzhiODliZjkwZWE4NzY1MWY0YWI0ZGQ4YjczMDA5MjM4YzA0ODI4ODEwZjJhMDZlMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YuaQ9iEWma07OcL2IBHnw-LCB6-j1NX0VjNwX_MGxjg)
> 
> Hello, you can follow these steps to install Flash Attention. You need to select the appropriate version of Flash Attention to download based on your Python, PyTorch, and CUDA versions.

I have another question:how many GPU memory do I need to run eval/eval.sh? I use two 24GB 4090 and failed

**Comment by echo840** [comment]
[issue](https://github.com/Yuliang-Liu/Monkey/issues/46)
A6000 or A800 GPU can be used for testing, and inference requires approximately 24.7GB GPU memory.
