### ISSUE TITLE
关于TextMonkey的Evaluate时计算score的问题

### ISSUE THREAD

**Issue by lxq0204** [Yuliang-Liu/Monkey#162]
非常感谢您的工作！
我在执行evaluate_vqa_doc.py时，在执行evaluate_exact_match_accuracy函数计算score时，这个score计算方法好像不准确？
![6cead2207eb6c777f0fb4b892ac3e8d](https://github.com/user-attachments/assets/32f68f7c-32ac-40e5-bc27-b49d239c3e32)

给出docvqa中的一个例子：
       answer是25%，annotation是['5', '5%', '5']
       如果按照程序中计算score的方法，这种answer是正确的，但是结果确实是错误的。那这样就会导致所有测试结果偏高，不知道我的理解是否正确？

**Comment by MelosY** [comment]
很感谢您的关注，这种评价match_accuracy是遵循ocrbench的评测方式，确实可能会存在您说的这种情况，因为回答过程中虚包了gt，这样评测主要是为了避免有时候回答内容过长所导致的问题，论文中其他模型的评测结果也是使用的一套评测范式，所以在模型比较中还是公平的。
