### ISSUE TITLE
question about Multi-level Description Generation

### ISSUE THREAD

**Issue by TyRantLQlyf** [Yuliang-Liu/Monkey#2]
Hi @MelosY @Yuliang-Liu . 
Will you open source related data and corresponding code in the future？

**Comment by MelosY** [comment]
Yes, we will release the related data and corresponding code soon.

**Comment by TyRantLQlyf** [comment]
@MelosY 

> Yes, we will release the related data and corresponding code soon.

thanks for your reply. I wonder when you will release the code. Im looking forward to generate my own caption with your method.

**Comment by MelosY** [comment]
My partner is working on it, and we'll release it by the end of the month if all goes well.

**Comment by trouble-maker007** [comment]
@MelosY I have some question about the Multi-level Description Generation:
1. In the second stage, use blip2 trained with coco to get the matching scores?
2. use blip2 trained with coco to calculate the all the generation(captions, object, etc) one bye one
3. use Chatgpt to merge the Multi-level Description, how to construct the in context prompt

**Comment by echo840** [comment]
Hello. We have submitted a pull request (PR) that includes the basic workflow for data generation.
