### ISSUE TITLE
请问论文中EST VQA的数据集是在某个网站评测的吗？我下载到的test数据只有问题没有答案

### ISSUE THREAD

**Issue by GITMrzk** [Yuliang-Liu/Monkey#21]

**Comment by GITMrzk** [comment]
我看到了本git中写了评测脚本，但是est vqa数据集的test部分的答案是在哪里找呢

**Comment by MelosY** [comment]
可以从这个网址下载ESTVQA https://cloudstor.aarnet.edu.au/plus/s/LSishuuSE5DBKJp

**Comment by Pe4nutZz** [comment]
同问，你这个链接点进去好像无法下载

> 可以从这个网址下载ESTVQA https://cloudstor.aarnet.edu.au/plus/s/LSishuuSE5DBKJp

**Comment by John-Ge** [comment]
你好，这个网站12月15日好像就失效了，请问你可以提供新的下载方式吗

**Comment by echo840** [comment]
您好，可以在https://github.com/Yuliang-Liu/MultimodalOCR里面下载“All Test Images”   其中包含ESTVQA的数据。

**Comment by GITMrzk** [comment]
> 您好，可以在https://github.com/Yuliang-Liu/MultimodalOCR 里面下载“All Test Images” 其中包含ESTVQA的数据。Monkey没有在ESTVQA上训练过，因此我们是从训练集中随机选取了一部分作为测试集，具体请参考 https://github.com/Yuliang-Liu/MultimodalOCR 。

那您其他数据集哪些是这个逻辑呢？我们验证过程中想对齐下~ @echo840

**Comment by echo840** [comment]
您好，只有ESTVQA和STVQA，具体请参考我们论文的附录。
