### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by eeric** [Yuliang-Liu/Monkey#25]
python demo.py

>>ConnectionResetError: [Errno 104] Connection reset by peer

 File "/Monkey/demo.py", line 287, in main
    _launch_demo(args, model, tokenizer)
  File "/Monkey/demo.py", line 252, in _launch_demo
    chatbot = gr.Chatbot(label='Monkey', elem_classes="control-height", height=600,avatar_images=("https://ooo.0x0.ooo/2023/11/09/OehsLx.png","https://ooo.0x0.ooo/2023/11/09/OehGBC.png"),layout="bubble",bubble_full_width=False,show_copy_button=True)

**Comment by ShuoZhang2003** [comment]
Perhaps you could consider substituting online images with local ones? I believe there might be a network-related issue causing the error.
