### ISSUE TITLE
训练数据示例

### ISSUE THREAD

**Issue by balabala2023** [Yuliang-Liu/Monkey#26]
您好，训练数据示例能否提供一下！

**Comment by echo840** [comment]
Hello, our training data was constructed following the format below:
{
        "id": "ChartQA/train/png/two_col_103562.png",
        "conversations": [
            {
                "from": "user",
                "value": "<img>img_path</img> As of 2021, how many championship titles had Ferrari won? Answer: "
            },
            {
                "from": "assistant",
                "value": "16"
            }
        ]
    }
