### ISSUE TITLE
A Slight Issue on Image Captioning

### ISSUE THREAD

**Issue by Hamster5295** [Yuliang-Liu/Monkey#27]
## Issue
As is shown in the pics below, Monkey seems to be distracted when analysing [THIS LOGO](https://hust.edu.cn/download/xiaohui.png).
![image](https://github.com/Yuliang-Liu/Monkey/assets/37259613/c730609e-2570-4ec8-bce2-a6ef7a745b0f)
![image](https://github.com/Yuliang-Liu/Monkey/assets/37259613/1b7a678d-01ac-4d5c-a453-66b3f4c2f383)
> Where is "湖北" ?
  
  
While Monkey produces wrong result on the school name at the first sight, it seems to have obtained the infomation, and answered correctly when asked in text afterwards: 
![image](https://github.com/Yuliang-Liu/Monkey/assets/37259613/36b48cc1-0d64-4ceb-a8fe-d0e14751d05f)

  
In my case, 7 tests were carried out, with 6 wrong answers and 1 without mentioning the school's name.  
The issue itself is not critical, through, but it gains its own necessity to be fixed :)

## Minimal Reproduce Steps
1. Download the [Logo](https://hust.edu.cn/download/xiaohui.png)
2. Visit the `Demo` or `Demo_chat` site
3. Upload the logo, then click on "Generate"
4. Wait for the result to come

**Comment by MelosY** [comment]
Thank you for your feedback.   I apologize if the model's responses were not accurate or specific to the Chinese context.   As an LMM, the responses are generated based on patterns and examples in the training data, which may not always align perfectly with specific regions or cultural contexts.  Wuhan and Hubei may come from the model's illusion and self-association, so there will be such problems in the caption.  Our model may be able to answer better questions that are more specific in direction.  We will continue to optimize in the next work.
