### ISSUE TITLE
Monkey训练image数据

### ISSUE THREAD

**Issue by balabala2023** [Yuliang-Liu/Monkey#35]
您好，Monkey训练的image数据，可以提供一下吗

**Comment by echo840** [comment]
Hello. If you urgently need data for your research, please contact me via email at zhangli123@hust.edu.cn.

**Comment by zhanghaobucunzai** [comment]
可以分享下数据集不？

**Comment by echo840** [comment]
> 可以分享下数据集不？

您好，我们训练json已经开源了。训练图片您可以按照上面的形似给我们发邮件（zhangli123@hust.edu.cn），我会及时地将我们整理好的zip文件分享给您。非常感谢您对Monkey的关注。

**Comment by zhanghaobucunzai** [comment]
好的  现在就发
