### ISSUE TITLE
加载tokenizer报错

### ISSUE THREAD

**Issue by ChingKwanCheung** [Yuliang-Liu/Monkey#37]
指定了tokenizer的本地路径还是报错：
ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

ValueError: We were not able to get the tokenizer using `AutoTokenizer.from_pretrained`
                    with the string that you have passed XXX/monkey-model. If you have a custom tokenizer, you can pass it as input.
                    For now, we only support quantization for text model. Support for vision, speech and multimodel will come later.

**Comment by MelosY** [comment]
建议参考我们的demo来构建Tokenizer：

> from monkey_model.tokenization_qwen import QWenTokenizer
