### ISSUE TITLE
The details of the 1.45M data

### ISSUE THREAD

**Issue by Coobiw** [Yuliang-Liu/Monkey#4]
Hello! Thanks for your great work! I am curious about the details of the 1.45M data you use for instruction tuning. I guess that it includes 400k(from CC3M), COCO datasets(around 100k-200k ?) and the downstream tasks data(like DocVQA, TextVQA, ...). Is it possible and convenient to reveal? Thank you in advance for your reading and replying.

**Comment by MelosY** [comment]
Yes, you are right, the other data is the downstream tasks data. We will reveal this detail in the modified version.
 Except for the detailed caption data, all the data is available on the official website, and we will publish this private data soon.
