### ISSUE TITLE
Questions about using LoRA

### ISSUE THREAD

**Issue by tanchaow** [Yuliang-Liu/Monkey#41]
Hello,
I want to make use of LORA, and I have added the the contents of model_qwen_nvdia3090.py. However I have a few questions:
1) Should I add '--use_lora' in the finetune/finetune_ds_debug.sh, just like Qwen-vl?
2) What should I do to **freeze other modules except LoRA and Resampler modules in finetune_multitask.py**.

**Comment by Leavelk** [comment]
Hello, I also have a question. After adding lora, using 3090 with 24G memory for training still causes OOM. Do I need to modify the length of the model input? For example, do not divide the image into 4 patches to reduce the model length? Could you give me some help?

**Comment by Leavelk** [comment]
@Yuliang-Liu  Hello, I also have a question. After adding lora, using 3090 with 24G memory for training still causes OOM. Do I need to modify the length of the model input? For example, do not divide the image into 4 patches to reduce the model length? Could you give me some help?

**Comment by alexwangmac** [comment]
@tanchaow Hello, could you tell me where is model_qwen_nvdia3090.py? thank you!

**Comment by ShuoZhang2003** [comment]
> @tanchaow Hello, could you tell me where is model_qwen_nvdia3090.py? thank you!

https://github.com/Yuliang-Liu/Monkey/blob/main/monkey_model/model_qwen_nvdia3090.py

**Comment by samaritan1998** [comment]
请问有解决方案了么？ finetune/finetune_ds_debug.sh 中添加了“--use_lora”，替换了modeling_qwen.py的文件，但是出现AttributeError: 'Linear' object has no attribute 'bias'的错误

**Comment by wanggebi1** [comment]
> 请问有解决方案了么？ finetune/finetune_ds_debug.sh 中添加了“--use_lora”，替换了modeling_qwen.py的文件，但是出现AttributeError: 'Linear' object has no attribute 'bias'的错误

请问这个问题解决了吗？

**Comment by samaritan1998** [comment]
> > 请问有解决方案了么？ finetune/finetune_ds_debug.sh 中添加了“--use_lora”，替换了modeling_qwen.py的文件，但是出现AttributeError: 'Linear' object has no attribute 'bias'的错误
> 
> 请问这个问题解决了吗？

lora配置为default_factory=lambda: ["c_attn", "attn.c_proj", "w1", "w2"]能解决，但是还是显存不够

**Comment by Ryoo72** [comment]
same question

**Comment by jweihe** [comment]
@Ryoo72  @samaritan1998 @alexwangmac @ShuoZhang2003 这个问题是由于peft版本的问题，可以试试更新到最新的
