### ISSUE TITLE
model inference

### ISSUE THREAD

**Issue by Zong-my** [Yuliang-Liu/Monkey#43]
I want to feed the model with a picture and a question each time and ask the model to return the corresponding answer. Is there any simple code implementation example for this?

**Comment by echo840** [comment]
Yes, here is an example code.
```python
from transformers import AutoModelForCausalLM, AutoTokenizer
checkpoint = "echo840/Monkey"
model = AutoModelForCausalLM.from_pretrained(checkpoint, device_map='cuda', trust_remote_code=True).eval()
tokenizer = AutoTokenizer.from_pretrained(checkpoint, trust_remote_code=True)
tokenizer.padding_side = 'left'
tokenizer.pad_token_id = tokenizer.eod_id
img_path = ""
question = ""
query = f'<img>{img_path}</img> {question} Answer: '

input_ids = tokenizer(query, return_tensors='pt', padding='longest')
attention_mask = input_ids.attention_mask
input_ids = input_ids.input_ids

pred = model.generate(
            input_ids=input_ids.cuda(),
            attention_mask=attention_mask.cuda(),
            do_sample=False,
            num_beams=1,
            max_new_tokens=10,
            min_new_tokens=1,
            length_penalty=1,
            num_return_sequences=1,
            output_hidden_states=True,
            use_cache=True,
            pad_token_id=tokenizer.eod_id,
            eos_token_id=tokenizer.eod_id,
            )
response = tokenizer.decode(pred[0][input_ids.size(1):].cpu(), skip_special_tokens=True).strip()
print(response)
```

**Comment by Zong-my** [comment]
> Yes, here is an example code.
> 
> ```python
> from transformers import AutoModelForCausalLM, AutoTokenizer
> checkpoint = "echo840/Monkey"
> model = AutoModelForCausalLM.from_pretrained(checkpoint, device_map='cuda', trust_remote_code=True).eval()
> tokenizer = AutoTokenizer.from_pretrained(checkpoint, trust_remote_code=True)
> tokenizer.padding_side = 'left'
> tokenizer.pad_token_id = tokenizer.eod_id
> img_path = ""
> question = ""
> query = f'<img>{img_path}</img> {question} Answer: '
> 
> input_ids = tokenizer(query, return_tensors='pt', padding='longest')
> attention_mask = input_ids.attention_mask
> input_ids = input_ids.input_ids
> 
> pred = model.generate(
>             input_ids=input_ids.cuda(),
>             attention_mask=attention_mask.cuda(),
>             do_sample=False,
>             num_beams=1,
>             max_new_tokens=10,
>             min_new_tokens=1,
>             length_penalty=1,
>             num_return_sequences=1,
>             output_hidden_states=True,
>             use_cache=True,
>             pad_token_id=tokenizer.eod_id,
>             eos_token_id=tokenizer.eod_id,
>             )
> response = tokenizer.decode(pred[0][input_ids.size(1):].cpu(), skip_special_tokens=True).strip()
> print(response)
> ```

ok，thanks
