### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers_modules.monkey.qwen_generation_utils'

### ISSUE THREAD

**Issue by fengmingfeng** [Yuliang-Liu/Monkey#48]
When I run the code,
from transformers import AutoModelForCausalLM, AutoTokenizer
checkpoint = "echo840/Monkey"
model = AutoModelForCausalLM.from_pretrained(checkpoint, device_map='cuda', trust_remote_code=True).eval()
tokenizer = AutoTokenizer.from_pretrained(checkpoint, trust_remote_code=True)
tokenizer.padding_side = 'left'
tokenizer.pad_token_id = tokenizer.eod_id
img_path = ""
question = ""
query = f'<img>{img_path}</img> {question} Answer: ' #VQA
# query = f'<img>{img_path}</img> Generate the detailed caption in English: ' #detailed caption

input_ids = tokenizer(query, return_tensors='pt', padding='longest')
attention_mask = input_ids.attention_mask
input_ids = input_ids.input_ids

pred = model.generate(
            input_ids=input_ids.cuda(),
            attention_mask=attention_mask.cuda(),
            do_sample=False,
            num_beams=1,
            max_new_tokens=10,
            min_new_tokens=1,
            length_penalty=1,
            num_return_sequences=1,
            output_hidden_states=True,
            use_cache=True,
            pad_token_id=tokenizer.eod_id,
            eos_token_id=tokenizer.eod_id,
            )
response = tokenizer.decode(pred[0][input_ids.size(1):].cpu(), skip_special_tokens=True).strip()
print(response)
the weight from 
![problem](https://github.com/Yuliang-Liu/Monkey/assets/98371935/92e47b4b-e008-4f07-b9f9-f5a0aa4ea719)
but have some problem.
>>> from transformers import AutoModelForCausalLM, AutoTokenizer
>>> model = AutoModelForCausalLM.from_pretrained("/root/autodl-tmp/monkey", device_map='cuda', trust_remote_code=True).eval()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/monkey/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 553, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/root/miniconda3/envs/monkey/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 500, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/root/miniconda3/envs/monkey/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 200, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/root/miniconda3/envs/monkey/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/.cache/huggingface/modules/transformers_modules/monkey/modeling_monkey.py", line 29, in <module>
    from .modeling_qwen import QWenModel,QWenPreTrainedModel,QWenLMHeadModel
  File "/root/.cache/huggingface/modules/transformers_modules/monkey/modeling_qwen.py", line 40, in <module>
    from .qwen_generation_utils import (
ModuleNotFoundError: No module named 'transformers_modules.monkey.qwen_generation_utils'
>>>

**Comment by echo840** [comment]
Hello, I think the reason is that the qwen_generation_utils.py file is not found in the folder .cache/huggingface/modules/transformers_modules/monkey/. Perhaps you can copy the qwen_generation_utils.py file and place it under the .cache/huggingface/modules/transformers_modules/monkey/ folder. It should be noted that we tested this code on another machine, and we were able to run it successfully without encountering this issue.

**Comment by geknow** [comment]
> Hello, I think the reason is that the qwen_generation_utils.py file is not found in the folder .cache/huggingface/modules/transformers_modules/monkey/. Perhaps you can copy the qwen_generation_utils.py file and place it under the .cache/huggingface/modules/transformers_modules/monkey/ folder. It should be noted that we tested this code on another machine, and we were able to run it successfully without encountering this issue. If there are any updates, I hope you can inform me. Thank you.

I encountered this issue too but fix it as what you say. But why this happen?

**Comment by echo840** [comment]
Perhaps you didn't use AutoModelForCausalLM.from_pretrained to directly download the model weights, but manually downloaded them?

> > Hello, I think the reason is that the qwen_generation_utils.py file is not found in the folder .cache/huggingface/modules/transformers_modules/monkey/. Perhaps you can copy the qwen_generation_utils.py file and place it under the .cache/huggingface/modules/transformers_modules/monkey/ folder. It should be noted that we tested this code on another machine, and we were able to run it successfully without encountering this issue. If there are any updates, I hope you can inform me. Thank you.
> 
> I encountered this issue too but fix it as what you say. But why this happen?

**Comment by geknow** [comment]
> Perhaps you didn't use AutoModelForCausalLM.from_pretrained to directly download the model weights, but manually downloaded them?
> 
> > > Hello, I think the reason is that the qwen_generation_utils.py file is not found in the folder .cache/huggingface/modules/transformers_modules/monkey/. Perhaps you can copy the qwen_generation_utils.py file and place it under the .cache/huggingface/modules/transformers_modules/monkey/ folder. It should be noted that we tested this code on another machine, and we were able to run it successfully without encountering this issue. If there are any updates, I hope you can inform me. Thank you.
> > 
> > 
> > I encountered this issue too but fix it as what you say. But why this happen?

<img width="436" alt="image" src="https://github.com/Yuliang-Liu/Monkey/assets/17638142/e9bf7d25-e028-42db-a497-899e1098892b">

<img width="962" alt="image" src="https://github.com/Yuliang-Liu/Monkey/assets/17638142/5d1a1108-9990-488b-bbed-025adab90e38">


Sorry, which one do you mean? I download from `https://huggingface.co/echo840/Monkey-Chat` and run the evaluation.

**Comment by fengmingfeng** [comment]
> Perhaps you didn't use AutoModelForCausalLM.from_pretrained to directly download the model weights, but manually downloaded them?
> 
> > > Hello, I think the reason is that the qwen_generation_utils.py file is not found in the folder .cache/huggingface/modules/transformers_modules/monkey/. Perhaps you can copy the qwen_generation_utils.py file and place it under the .cache/huggingface/modules/transformers_modules/monkey/ folder. It should be noted that we tested this code on another machine, and we were able to run it successfully without encountering this issue. If there are any updates, I hope you can inform me. Thank you.
> > 
> > 
> > I encountered this issue too but fix it as what you say. But why this happen?

I just download the model in my computer,and outline load it,but when i download it

**Comment by fengmingfeng** [comment]
> > Perhaps you didn't use AutoModelForCausalLM.from_pretrained to directly download the model weights, but manually downloaded them?
> > > > Hello, I think the reason is that the qwen_generation_utils.py file is not found in the folder .cache/huggingface/modules/transformers_modules/monkey/. Perhaps you can copy the qwen_generation_utils.py file and place it under the .cache/huggingface/modules/transformers_modules/monkey/ folder. It should be noted that we tested this code on another machine, and we were able to run it successfully without encountering this issue. If there are any updates, I hope you can inform me. Thank you.
> > > 
> > > 
> > > I encountered this issue too but fix it as what you say. But why this happen?
> 
> <img alt="image" width="436" src="https://private-user-images.githubusercontent.com/17638142/303208248-e9bf7d25-e028-42db-a497-899e1098892b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNjUwMjMsIm5iZiI6MTcwNzM2NDcyMywicGF0aCI6Ii8xNzYzODE0Mi8zMDMyMDgyNDgtZTliZjdkMjUtZTAyOC00MmRiLWE0OTctODk5ZTEwOTg4OTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDAzNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNjc5OTc3ZjFmZTcwNGM2YjI1OWQzOGRlMjdmMWY5ODE5YTNjMGE1YTdjZmQ4ODA5MWQxM2FkNDVmMGNmOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2mMWrUqlzTIA1nHA-uM1FMhW4cQnTBq5JH6f8Zrq8xk"> <img alt="image" width="962" src="https://private-user-images.githubusercontent.com/17638142/303208291-5d1a1108-9990-488b-bbed-025adab90e38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNjUwMjMsIm5iZiI6MTcwNzM2NDcyMywicGF0aCI6Ii8xNzYzODE0Mi8zMDMyMDgyOTEtNWQxYTExMDgtOTk5MC00ODhiLWJiZWQtMDI1YWRhYjkwZTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDAzNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZDE1MGI5NjYwMTFlOTkzOTY4ZWU5YzI4YWU4ODExNjc1M2ZjMzMzMjExOWQxZWVjZDFhMmJjMTE5YjliYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nqjvmqb84fT93vBoGafhBZKpPN1zbInQMamYItnkK94">
> Sorry, which one do you mean? I download from `https://huggingface.co/echo840/Monkey-Chat` and run the evaluation.
when i download it inline,it was work sucessully.
