### ISSUE TITLE
Performance compared to llava?

### ISSUE THREAD

**Issue by eddyrivers10** [Yuliang-Liu/Monkey#5]
Hi authors, I ran images in your demo but I got a much worse results compared to Llava. The captions are very short even if I follow the same prompt for detailed description in the paper and I used the same image for both llava and this. The higher resolution also doesn't capture the small text in the correct location. Is there something wrong with the demo? I cannot get results close to anything shown in the paper.

Can you explain how you added perceiver resampler too? Since perceiver resampler is used for videos, is the temporal dimension used for the number of images?

Thanks in advance.

**Comment by Yuliang-Liu** [comment]
@eddyrivers10

Dear Eddy,

Could you kindly provide some images for us? We need them to identify the potential causes of the issue we're facing. We've conducted numerous comparisons with LLaVA 1.5 and believe that our results should at least match its performance. Your assistance in sharing these images would be greatly appreciated.

**Comment by YULUOYUNZHI** [comment]
I chose 5 images that occurred today for testing, which I uploaded for analysis. The first four are from today's 2023 League of Legends World Championship, and the fifth is a random shot taken for testing purposes. Based on the images I uploaded, I find that in most cases, Monkey testing performs better than Llava 1.5.
![image](https://github.com/Yuliang-Liu/Monkey/assets/131934138/4b7dcfb1-55cc-4d44-946a-0560f50ff388)
![image](https://github.com/Yuliang-Liu/Monkey/assets/131934138/0d71b04b-de44-4841-aa39-e430dd28cc46)
![image](https://github.com/Yuliang-Liu/Monkey/assets/131934138/6684ce39-b8f3-490b-82b4-b9b2cc685dd3)
![image](https://github.com/Yuliang-Liu/Monkey/assets/131934138/bbc2f9e9-cf86-446e-b055-a9391c13751e)
![image](https://github.com/Yuliang-Liu/Monkey/assets/131934138/8fd5bf68-6485-4441-aab7-4fea847de11d)

**Comment by eddyrivers10** [comment]
Hi, I just used the default image of the man ironing on the back of his car from the llava dem https://llava.hliu.cc/. When I asked for a detailed caption I get `A man is ironing his shirt on the back of a car.`

Second example I tried was the water image from the llava demo too. The caption received is `A long wooden pier on a lake surrounded by trees.`.

The captions are very short compared to llava. However llava hallucinates more as the captions are longer. Does the demo use the same decoding length? I wonder how you can make Monkey give descriptive sentences without hallucinating. Thanks!

**Comment by echo840** [comment]
![T4)27088~8LUN~K7RKLVW)E](https://github.com/Yuliang-Liu/Monkey/assets/87795401/b1303b5c-1b12-4a33-9aa5-a9d4f15bd0b4)
![3BFF HB)(5} Q{%}K(19I0F](https://github.com/Yuliang-Liu/Monkey/assets/87795401/13e7fd81-ef9b-4453-87cf-8027ecfac59d)
![2P$Q)PQ5QVGCI4EIWS}ML Q](https://github.com/Yuliang-Liu/Monkey/assets/87795401/08657fd2-30d6-4e5a-9264-5d50f5397844)
![U5~ P}SC5B~ Z)(G)(IIMXG](https://github.com/Yuliang-Liu/Monkey/assets/87795401/0cfd9fe8-fb18-4006-9e0f-f25d306109a5)

![image](https://github.com/Yuliang-Liu/Monkey/assets/87795401/18cdb556-415b-4d83-8e79-a549ad04f368)
Hello. You should click the “Generate” button to get a detailed description of the image. For the VQA task, we utilize the following format: "[question] Answer: [answer]." For the detailed caption task, we employ the format: "Generate the detailed caption in English: [caption]."  If you provide the input 'Generate the detailed caption in English:' and click “submit” button, the model's input will be 'Generate the detailed caption in English: Answer:'. This input deviates from what we were trained on.

**Comment by eddyrivers10** [comment]
Hi authors, sorry if I used it wrongly, I haven't had the chance to check the demo again since the web traffic is high now. But it looks like I have clicked on the wrong option which is why the captions are so short.

For the captions above it looks like they are shorter but more factual. Do you know if there's a comparison on hallucination versus llava and other larger resolution models? Thank you!

**Comment by shipengai** [comment]
@Yuliang-Liu 。In Monkey paper，  Is “llava1.5 pretrained with CC3M” which the Table 6  says same with original llava1.5？这个模型训练数据是跟原始的llava1.5-13b一样吗

**Comment by echo840** [comment]
Hello. Our experiments involved a comparative analysis where we pretrained LLaVA1.5 using the same original data from LLaVA, with the modification of replacing 427k text with our generated annotations. The instruction tuning data  were exclusively sourced from LLaVA1.5.

**Comment by shipengai** [comment]
@echo840  Thanks for your reply.  when pretrained by llava data, mmbench score is 68.3 that higher than llav1.5 which is 67.7。 This is an amazing result。
