### ISSUE TITLE
modeling_qwen_nvdia3090.py

### ISSUE THREAD

**Issue by Ryoo72** [Yuliang-Liu/Monkey#53]
"In "Add LoRA: You need to replace the contents of model_qwen.py with the contents of model_qwen_nvdia3090.py," it seems there is a typo in model_qwen_nvdia3090.py. To reduce confusion, please change it to modeling_qwen_nvdia3090.py."

**Comment by echo840** [comment]
Thank you for your reminder. We have already corrected the typo error.
