### ISSUE TITLE
Question about using other LLM models as pre-training models

### ISSUE THREAD

**Issue by Sanster** [Yuliang-Liu/Monkey#54]
Thank you for sharing your paper, code, and model weights! I have a question regarding the choice of pre-trained LLM model. Monkey used the Qwen-VL-7b pre-trained model, and as mentioned in the paper, the vision encoder of this model has already been pre-trained with LLM weights, allowing for direct instruct fine-tuning in the Monkey paper. 

My question is: Have you tried using a method similar to LLaVA to first pre-train an adapter (with the benefit of being able to use a larger LLM model, such as Qwen-14b), and then use Monkey's approach (divided patches + image resampler) for instruct fine-tuning? How do you think this approach would perform? Thanks

**Comment by YULUOYUNZHI** [comment]
Thank you for your affirmation.We have already tried on the llava framework, and the results are as follows.
![image](https://github.com/Yuliang-Liu/Monkey/assets/131934138/4ba531d8-250f-4a13-a3a7-7dbe5c7401d1)
We are currently conducting replacement verification on a larger llm.

**Comment by jpWang** [comment]
@YULUOYUNZHI Hi, I want to ask that the newest TextMonkey uses Qwen-VL-base or Qwen-VL-Chat as initialization?  And I want to ask the reason that why not use another one? Thanks !

**Comment by YULUOYUNZHI** [comment]
> @YULUOYUNZHI Hi, I want to ask that the newest TextMonkey uses Qwen-VL-base or Qwen-VL-Chat as initialization? And I want to ask the reason that why not use another one? Thanks !

**Comment by YULUOYUNZHI** [comment]
> @YULUOYUNZHI Hi, I want to ask that the newest TextMonkey uses Qwen-VL-base or Qwen-VL-Chat as initialization? And I want to ask the reason that why not use another one? Thanks !

The TextMonkey uses Qwen-VL-base, and generally speaking, the chat version undergoes downstream fine-tuning, which is more in line with human preferences, while the VL version is more adaptable.
