### ISSUE TITLE
Questions about train data of TextMonkey†

### ISSUE THREAD

**Issue by jpWang** [Yuliang-Liu/Monkey#59]
Hi, thanks for these great works ~
I have some questions about the train data of TextMonkey.

![image](https://github.com/Yuliang-Liu/Monkey/assets/52776462/8f398803-6dc0-47a1-8708-89d65a44fdcd)

1. As shown in Table 2, does this mean that the results of TextMonkey on FUNSD/SROIE/POIE in Table 3 are zero-shot?
2. In section 3.4 it is said that TextMonkey† uses further structured data. I want to ask that, are these structured data are still only acquired from Table 2? does this mean that the results of TextMonkey† on FUNSD/SROIE/POIE in Table 3 are still zero-shot?
Thanks!

**Comment by MelosY** [comment]
Yes, the results of TextMonkey and TextMonkey† on FUNSD/SROIE/POIE in Table 3 are always zero-shot. These structured data are still only acquired from Table 2 but with more detailed description.
