### ISSUE TITLE
Issue with Image Path not Being Correctly Replaced in Training Script

### ISSUE THREAD

**Issue by jweihe** [Yuliang-Liu/Monkey#60]
I encountered a FileNotFoundError when trying to run a training script that involves reading image paths. The script is supposed to decode image paths from input_ids, and then load these images for further processing. However, the paths are not correctly formed, leading to a FileNotFoundError.

Here's the relevant code snippet:

```python
if past_key_values is None and torch.any(input_ids == self.config.visual['image_start_id']):
    bos_pos = torch.where(input_ids == self.config.visual['image_start_id'])
    eos_pos = torch.where(input_ids == self.config.visual['image_start_id'] + 1)
    assert (bos_pos[0] == eos_pos[0]).all()
    img_pos = torch.stack((bos_pos[0], bos_pos[1], eos_pos[1]), dim=1)
    images = []
    for i, a, b in img_pos:
        image = input_ids[i][a + 1 : b - 1].tolist()
        image = image[:image.index(self.config.visual['image_start_id'] + 2)]
        images.append(bytes(image).decode('utf-8'))
    print('images', images)
    windows, images_448 = self.visual.encode(images)
```

The error I receive is: FileNotFoundError: [Errno 2] No such file or directory: '<Your_Image_Dir_Path>/gqa/images/2153.jpg'

Upon investigation, I realized the placeholder <Your_Image_Dir_Path> in the training JSON file was not automatically replaced, which seems to be the cause of the issue.

I am uncertain if this is a bug in the code or if I have missed a step in the setup process that is responsible for replacing these placeholders with actual paths.

Could you please help clarify if this behavior is expected and suggest a potential solution or workaround? Any insights into whether this is a coding mistake or a setup oversight on my part would be greatly appreciated.

**Comment by echo840** [comment]
Hi. You should manually replace "<Your_Image_Dir_Path>" with the directory path of your images, such as "./data".

**Comment by jweihe** [comment]
Solved. Thank you!
