### ISSUE TITLE
AttributeError: 'Linear' object has no attribute 'bias' during LoRA Training

### ISSUE THREAD

**Issue by jweihe** [Yuliang-Liu/Monkey#61]
**Description:**
When attempting to train a model using LoRA, an AttributeError is encountered, indicating that a 'Linear' object has no attribute 'bias'. This issue arises specifically during the forward pass of the model, within the context of utilizing attention mechanisms that apparently involve linear layers without a bias term.
**Actual Behavior:**
Training fails with the following traceback, highlighting an AttributeError related to accessing the bias attribute of a Linear layer:

` Traceback (most recent call last):
  File "finetune_multitask.py", line XYZ, in <module>
    train()
  ... (omit irrelevant traceback parts) ...
  File "torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "modeling_monkey.py", line 76, in forward
    patch_list.append(self.visual(image_patch,idx=lora_idx))
  ... (omit irrelevant traceback parts) ...
  File "visual.py", line 504, in forward
    x = self.attn_pool(x)
  File "torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "visual.py", line 167, in forward
    out = self.attn(
  File "torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/nn/modules/activation.py", line 1209, in forward
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Linear' object has no attribute 'bias'`
**Additional Context:**
This error suggests that the training process attempts to access the bias attribute of a Linear module which was presumably configured without bias or the attribute was somehow unset. This is occurring within the context of a LoRA-enhanced model, suggesting that the issue may be related to how LoRA adaptations are integrated with the model's architecture.

What should I do to sovle this problem？

**Comment by jweihe** [comment]
Have Solved it

**Comment by ganzijie** [comment]
怎么解决的，我也遇到了，可以说下吗

**Comment by JeffRody** [comment]
请教一下 同问
