### ISSUE TITLE
About the training dataset in Multi-task Training of Monkey 

### ISSUE THREAD

**Issue by lllyyqq** [Yuliang-Liu/Monkey#62]
In your paper, in section 3.3, you mentioned the training data for Multi-task Training as shown in the figure. However, in section 4.1, during the training phase, you mentioned using your proposed Multi-level Description Generation method to regenerate approximately 427k image-text pairs from the CC3M dataset. I have two questions: 
**1. Does this generated 427k CC3M dataset also include the training data for the Multi-task Training task?** 
**2. Is your training phase only comprised of one Multi-task Training stage for fine-tuning QWEN-VL?**
![image](https://github.com/Yuliang-Liu/Monkey/assets/88069893/88c61acc-69d4-4c7a-acaf-d063b0d3c29c)

**Comment by echo840** [comment]
Yes, to ensure the balance of the different datasets, we used the generated detailed description data of 213k to train Monkey. In the ablation experiments on llava1.5, we used all 427k detailed description data. Monkey's training consists of only one stage.
