### ISSUE TITLE
TextMonkey 在线demo

### ISSUE THREAD

**Issue by hsl20130659** [Yuliang-Liu/Monkey#65]
大佬好，TextMonkey 在线demo不能访问了，可以再开放测试吗？谢谢！

**Comment by lynquantumman** [comment]
同问

**Comment by truebit** [comment]
本机网络要可以访问amazonaws才行

**Comment by echo840** [comment]
您好，text monkey的demo现在是可以访问的

**Comment by echo840** [comment]
> > 您好，text monkey的demo现在是可以访问的
> 
> 又不能访问了

非常抱歉。我们服务器的地址隔几天就会自动刷新，更新了之后需要更新dns配置，才能正常访问。
今天早上我们服务器的地址被刷新了，我已经对dns配置进行更新，现在demo可以正常访问了。非常感谢您的提醒，我们会及时更新服务器配置。

**Comment by weirman** [comment]
@echo840 大佬好，服务又不能访问了，辛苦你这边再处理一下

**Comment by echo840** [comment]
貌似现在是好的，可能网络波动了一下。

> @echo840 大佬好，服务又不能访问了，辛苦你这边再处理一下

**Comment by weirman** [comment]
http://vlrlab-monkey.xyz:7684/   emmm 是这个网站么？

**Comment by echo840** [comment]
> http://vlrlab-monkey.xyz:7684/ emmm 是这个网站么？

非常抱歉，由于资源限制我们只部署了monkey-chat的demo，网址是http://vlrlab-monkey.xyz:7681/， 您发的这个是Textmonkey之前的网址，现在没有部署了。

**Comment by weirman** [comment]
哦哦，好的，谢谢大佬。大佬可以说下部署时候的最低硬件配置吗？

**Comment by echo840** [comment]
> 哦哦，好的，谢谢大佬。大佬可以说下部署时候的最低硬件配置吗？

目前的demo是部署在单卡a6000上面。
