### ISSUE TITLE
冻结LLM：需要在finetune_multitask.py中冻结除LoRA和Resampler模块的其他模块

### ISSUE THREAD

**Issue by jweihe** [Yuliang-Liu/Monkey#66]
请问该步骤如何实现呢

**Comment by jweihe** [comment]
"c_attn", "attn.c_proj", "w1", "w2"这四层不也是LLM内部的吗，但是代码里面也还是打开的

**Comment by echo840** [comment]
```python
for k,v in model.named_parameters():
     if "lora" in k :
           v.requires_grad_(True)
if training_args.fix_llm and hasattr(model,'transformer') and hasattr(model.transformer,'h'):
      model.transformer.h.requires_grad_(False)
      model.transformer.wte.requires_grad_(False)
      model.transformer.ln_f.requires_grad_(False)
      model.lm_head.requires_grad_(False)
```
您可以参考上面的代码冻结对应参数。

**Comment by jweihe** [comment]
好的，谢谢！此外还有一个问题，config中配置的seq_length为2048，但是实际上VisualMRC数据集里面大部分图片的大小是大于1792*1792的，这意味着这些图片会被裁剪为超过4*4+1=17个patch，每个image patch占用的token是256，这样算出来的结果是大于2048的，和text token到一起之后超出了2048的限制，这是不是意味着多余的token全部被裁剪掉了，这个数据集上的训练全部都是没有意义的？

**Comment by echo840** [comment]
您好，所有图像我们都是resize到896×896进行处理的，一共是（2*2+1）*256=1280个token ， config中配置的seq_length也可以设置为4096.

**Comment by jweihe** [comment]
所以如果是448*896的图片，也会先resize到896*896然后crop，这样似乎不太合理，不过我明白您的意思了，感谢！
