### ISSUE TITLE
性能比在线demo差很多，本地版输出都很简单且短

### ISSUE THREAD

**Issue by charliedream1** [Yuliang-Liu/Monkey#68]
性能比在线demo差很多，本地版输出都很简单且短

max_new_tokens设的250，但总是只出10个字左右，答复都很简单。和在线demo性能差距太大了，模型是从这里下的：https://huggingface.co/echo840/Monkey

请问是什么问题？

**Comment by echo840** [comment]
您好，我们目前部署的是新版本的monkey。  您可以本地使用"https://huggingface.co/echo840/Monkey-Chat"，交互体验会有提升。

**Comment by charliedream1** [comment]
本地部署的是从https://huggingface.co/echo840/Monkey这里下载的，但本地版输出都很简单且短，效果比线上差了很多，是开源的这个和线上的不是一个版本吗？

但本地部署这个效果感觉比qwen-vl， llava差了很远，还是我哪里配置错误？用的就是demo.py跑的

**Comment by charliedream1** [comment]
好的，我试试，谢谢

**Comment by echo840** [comment]
您好，Monkey原始版本只在一些VQA和详细描述数据上进行训练，没有用对话数据进行训练，而VQA数据的gt都比较短，所以原始版本的Monkey也倾向生成较短的回答，但在相应任务上的问答准确性可能更好。Demo版本和Monkey-Chat都进行了相应优化。

**Comment by charliedream1** [comment]
好的，谢谢，我试一下。刚才把chat版，看成和base版是同一个了
