### ISSUE TITLE
AttributeError: 'QWenTokenizer' object has no attribute 'IMAGE_ST'

### ISSUE THREAD

**Issue by charliedream1** [Yuliang-Liu/Monkey#69]
运行demo.py时报这个错

**Comment by echo840** [comment]
您好，这应该是transformer版本的问题，请使用transformers==4.32.0

**Comment by charliedream1** [comment]
好，谢谢，我试试



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 29, 2024 15:56 PM
To: ***@***.***&gt;;
Cc: "Optimus ***@***.******@***.***&gt;;
Subject: Re: [Yuliang-Liu/Monkey] AttributeError: 'QWenTokenizer' object hasno attribute 'IMAGE_ST' (Issue #69)




 
您好，这应该是transformer版本的问题，请使用transformers==4.32.0
