### ISSUE TITLE
looking forward to TextMonkey model weight and sample code

### ISSUE THREAD

**Issue by truebit** [Yuliang-Liu/Monkey#72]
Is there any time schedule on TextMonkey model weight and sample code releasing date? 
Thanks

**Comment by echo840** [comment]
We will realse it in the next few days. Thank you.

**Comment by Yuliang-Liu** [comment]
Hi, code is released. Please let us know if there is anything we can help. https://github.com/Yuliang-Liu/Monkey/pull/75
