### ISSUE TITLE
Inconsistency in Performance: Inference Code Yields Poor Results Compared to Online Demo

### ISSUE THREAD

**Issue by ashu0013** [Yuliang-Liu/Monkey#73]
Experiencing discrepancies: while the online demo produces satisfactory output with the same document and query, but the inference code yields unsatisfactory results.Why its happening and  how to resolve this issue.

**Comment by Yuliang-Liu** [comment]
Because the demo is now using the updated version of Monkey. We will release it soon. Thanks for your attention

**Comment by ashu0013** [comment]
Any timeline for this ??

**Comment by Yuliang-Liu** [comment]
Maybe mid to late May
