### ISSUE TITLE
run demo.py error

### ISSUE THREAD

**Issue by cqray1990** [Yuliang-Liu/Monkey#76]
did flash_attn  must be installed ?
 
assert flash_attn_unpadded_func is not None, (
NameError: name 'flash_attn_unpadded_func' is not defined

**Comment by echo840** [comment]
Yes, we used flash_attn. You can download the corresponding version of flash_attention from https://github.com/Dao-AILab/flash-attention/releases/ and use the following code to install:
···python
pip install flash_attn-2.3.5+cu117torch2.0cxx11abiFALSE-cp310-cp310-linux_x86_64.whl --no-build-isolation
···
