### ISSUE TITLE
Does the TextMoney vit has pretrain model?

### ISSUE THREAD

**Issue by luohao123** [Yuliang-Liu/Monkey#77]
Is it just training from scratch?

**Comment by echo840** [comment]
We initialize from QwenVL model.

**Comment by luohao123** [comment]
Does the archecture has any changes compare to original QwenVL?

**Comment by echo840** [comment]
> Does the archecture has any changes compare to original QwenVL?

Yes, you can refer to our paper https://arxiv.org/abs/2403.04473 .

**Comment by luohao123** [comment]
Actually except for the input reoslution, I didn't found any changes to the QwenVL arch?/?

**Comment by echo840** [comment]
> Actually except for the input reoslution, I didn't found any changes to the QwenVL arch?/?

Hello, we haven't modified the original architecture of QwenVL, but we have incorporated "Shifted Attention Layers" to incorporate cross-window connectivity while expanding the input resolutions. Furthermore, we have introduced a "Token Resampler" to eliminate redundant visual tokens.
There are two primary modifications in TextMonkey, illustrated in the figure below: "Shifted Attention Layers" and "Token Resampler."
![image](https://github.com/Yuliang-Liu/Monkey/assets/87795401/3a96b769-baec-458e-9250-9ce29f6f4945)

**Comment by luohao123** [comment]
Hello, from the graph I saw a Image Resample and a TokenResampler, what's the difference?

The resample just a preciever, how does it sampling Image?

And, how do u choose how many tokens to resample from raw'?

**Comment by echo840** [comment]
Hello. The image resampler utilizes a set of learnable queries as inputs. The token resampler samples the top k most important tokens from image features as query inputs, then performs cross-attention with the global image features to reduce the number of input tokens. We select the top 50% most important tokens as inputs. For detailed information, please refer to our paper and code.

**Comment by luohao123** [comment]
What's the differences compare to qwenvl's Resampler//?

**Comment by echo840** [comment]
Hello. There are some differences in architecture. You can refer to the code for more details.
https://github.com/Yuliang-Liu/Monkey/blob/main/monkey_model/text_monkey/resampler.py
https://github.com/Yuliang-Liu/Monkey/blob/main/monkey_model/text_monkey/visual_text.py
