### ISSUE TITLE
Online Demo

### ISSUE THREAD

**Issue by jiawei-liu1103** [Yuliang-Liu/Monkey#79]
作者您好，发现在线demo又无法访问了，是服务器地址刷新了吗？麻烦您更新一下服务器配置，感谢！

**Comment by echo840** [comment]
您好，感谢您的提醒，我们会尽快检查并修复。

**Comment by echo840** [comment]
经过检查，发现是我们服务器上的存储空间用完了，现在清理了空间。demo现在可以正常访问了。感谢您的提醒！
