### ISSUE TITLE
Pretrained weight for text monkey

### ISSUE THREAD

**Issue by MartinYYYYan** [Yuliang-Liu/Monkey#80]
Hi! When I tried to use the TextMonkey to analyze local scanned pdf file, I found the pretrained pytorch_model.bin is not existed in huggingface repository: https://huggingface.co/MelosY/TextMonkey/tree/main. Do you have any plans to upload the full Pretrained-Weights recently?
I am really appreciated for your contribution and look forward to your further research

**Comment by echo840** [comment]
Due to network issues, the model weights have not been uploaded to Hugging Face yet. However, we have already uploaded them to https://www.modelscope.cn/models/lvskiller/TextMonkey/. We will upload the model weights to Hugging Face in the future.

**Comment by Yuliang-Liu** [comment]
![微信截图_20240417112044](https://github.com/Yuliang-Liu/Monkey/assets/34134635/00ead12d-ddd7-4e65-9709-839badbc02bf)
This button directs to the model.

**Comment by nomadlx** [comment]
> ![微信截图_20240417112044](https://private-user-images.githubusercontent.com/34134635/323060022-00ead12d-ddd7-4e65-9709-839badbc02bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzM1NTgsIm5iZiI6MTcxNTc3MzI1OCwicGF0aCI6Ii8zNDEzNDYzNS8zMjMwNjAwMjItMDBlYWQxMmQtZGRkNy00ZTY1LTk3MDktODM5YmFkYmMwMmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDExNDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiM2ViMWZjZjFjMThiMTlmNmVlYmZmNTFhMGRjNDcyMzZkMjAyYmJlMDM5MTg5MzY0MjgxYWRiNDMzMmM0NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fK1rtWVIn_Y2q48wY3-7f5VMOYWCLujlRm82RQvjFtY) This button directs to the model.

Is it used in the same way as [monkey-chat](https://huggingface.co/echo840/Monkey-Chat)?
