### ISSUE TITLE
textMonkey data release

### ISSUE THREAD

**Issue by BingranHu** [Yuliang-Liu/Monkey#81]
May I ask when the training data used by textMonkey will be released?  Is it the same as the data in Monkey [https://pan.baidu.com/s/1svSjXTxWpI-3boALgSeLlw](url)?

**Comment by echo840** [comment]
Hello. We have uploaded the training JSON for TextMonkey to https://www.modelscope.cn/datasets/lvskiller/TextMonkey_data/summary. The image data for TextMonkey is currently being uploaded to Hugging Face. Please be patient as the upload process may take some time. It's worth noting that TextMonkey and Monkey use different datasets.
![image](https://github.com/Yuliang-Liu/Monkey/assets/87795401/7be0d521-d47b-4fd3-be7b-eece219baeb7)

**Comment by MelosY** [comment]
I have upload the image data, welcome to use it.

**Comment by BingranHu** [comment]
> Hello. We have uploaded the training JSON for TextMonkey to https://www.modelscope.cn/datasets/lvskiller/TextMonkey_data/summary. The image data for TextMonkey is currently being uploaded to Hugging Face. Please be patient as the upload process may take some time. It's worth noting that TextMonkey and Monkey use different datasets.
> ![image](https://private-user-images.githubusercontent.com/87795401/323185709-7be0d521-d47b-4fd3-be7b-eece219baeb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTAxMDgsIm5iZiI6MTcxMzQwOTgwOCwicGF0aCI6Ii84Nzc5NTQwMS8zMjMxODU3MDktN2JlMGQ1MjEtZDQ3Yi00ZmQzLWJlN2ItZWVjZTIxOWJhZWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAzMTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YTE5YTEyZjU2MDdhMTg0MWQyNjBhNTc5YTk1NzcwMzVmYjJmZmUwMGE5MDkwOTMzY2NhMGNjODE5NzIyNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XtG55YBdO6KsWR0KU9Y4Vz3mRbC_FxI6w9SCyF1-9-w)

Thank you so much for your prompt response！
