### ISSUE TITLE
TextMonkey问题

### ISSUE THREAD

**Issue by songyanbei** [Yuliang-Liu/Monkey#82]
![WechatIMG111039](https://github.com/Yuliang-Liu/Monkey/assets/33091648/8118d795-5dbf-43c4-b72a-36ab726f38d1)

作者你好，在看论文和训练数据时，我对论文中的table1部分有两个疑问，如上图红框所示。
问题1: table1里的Text Recognition的box是(x1,y1),(x2,y2)两个点，但我发现在实际的json中只有中心点坐标，这里的描述和应用是否存在差异。
问题2：关于坐标归一化的描述是否有误，是x/hr还是y/hr?

**Comment by pikerbright** [comment]
So for the released TextMonkey model, is it trained using <box>(x1,y1),(x2,y2)</box> label data?
