### ISSUE TITLE
Data Access

### ISSUE THREAD

**Issue by daniel-z-kaplan** [Yuliang-Liu/Monkey#84]
I'm trying to replicate this paper for a work I am doing, but downloading the training data is very difficult without a Baidu account.

Is it possible to mirror the data to somewhere like Huggingface, for easier replication?

**Comment by echo840** [comment]
Thank you for your suggestions. We will upload the data to Hugging Face in the next few days. Due to network issues, this process might take some time. Please be patient and wait for the update.

**Comment by echo840** [comment]
Hello, you can download the data now. To concatenate zip files, use the command cat Monkey_Train_data.zip.* > Monkey_Train_data.zip .
