### ISSUE TITLE
TextMonkey RuntimeError

### ISSUE THREAD

**Issue by jweihe** [Yuliang-Liu/Monkey#85]
I encountered an issue while trying to run the TextMonkey model. Here's the traceback of the error message:
```
  File "/group/40034/jweihe/code/ocr-mllm/TextMonkey/Monkey/monkey_model/modeling_textmonkey.py", line 77, in forward
    return super().forward(input_ids,
  File "/group/40034/jweihe/code/ocr-mllm/TextMonkey/Monkey/monkey_model/modeling_qwen.py", line 817, in forward
    hidden_states[i][a + 1 : b] = images[idx]
RuntimeError: The expanded size of the tensor (1280) must match the existing size (768) at non-singleton dimension 0.  Target sizes: [1280, 4096].  Tensor sizes: [768, 4096]
```

The error seems to be due to a mismatch in tensor sizes. The expanded size of the tensor (1280) must match the existing size (768) at non-singleton dimension 0. However, the target sizes are [1280, 4096] and the tensor sizes are [768, 4096].

**Comment by zws-2019** [comment]
> I encountered an issue while trying to run the TextMonkey model. Here's the traceback of the error message:
> 
> ```
>   File "/group/40034/jweihe/code/ocr-mllm/TextMonkey/Monkey/monkey_model/modeling_textmonkey.py", line 77, in forward
>     return super().forward(input_ids,
>   File "/group/40034/jweihe/code/ocr-mllm/TextMonkey/Monkey/monkey_model/modeling_qwen.py", line 817, in forward
>     hidden_states[i][a + 1 : b] = images[idx]
> RuntimeError: The expanded size of the tensor (1280) must match the existing size (768) at non-singleton dimension 0.  Target sizes: [1280, 4096].  Tensor sizes: [768, 4096]
> ```
> 
> The error seems to be due to a mismatch in tensor sizes. The expanded size of the tensor (1280) must match the existing size (768) at non-singleton dimension 0. However, the target sizes are [1280, 4096] and the tensor sizes are [768, 4096].

Here's how I did it:
```
hidden_states[i][a + 1 : b] = images[idx]
# be modified:
hidden_states[i][a + 1 : b].data = images[idx]
```
Did you do full parameter tuning or LORA? Are you using a 40GB or 80GB graphics card?

**Comment by jweihe** [comment]
Following this method, I successfully ran the code, thank you! However, when I tried to run the code for testing, the output images were all garbled. Have you tested it? Could it be that there are still bugs in the code itself? I haven't tried fine-tuning yet.

**Comment by jweihe** [comment]
When I tested this image,
![4](https://github.com/Yuliang-Liu/Monkey/assets/50818235/fa8e3985-cd6c-4afb-88f9-8e27891c4223)
 the input prompt was "Read all the text in the image." The output result is 
> Picture 1: UUUQUQUUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUPicture 1: UUUQUQUUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQUQU

**Comment by zws-2019** [comment]
Could you please tell us the following questions so as to further locate the problem?
```
Did you do full parameter tuning or LORA? Are you using a 40GB or 80GB graphics card?
```

**Comment by jweihe** [comment]
Not yet, I am still in the testing phase.

**Comment by jweihe** [comment]
I am using a 32G V100

**Comment by zws-2019** [comment]
> Not yet, I am still in the testing phase.

tokenizer needs to add a configuration parameter
```
tokenizer.IMG_TOKEN_SPAN = 768
```

**Comment by zws-2019** [comment]
> Not yet, I am still in the testing phase.

tokenizer needs to add a configuration parameter
```
tokenizer.IMG_TOKEN_SPAN = 768
```
and remove the "data"
```
hidden_states[i][a + 1 : b].data = images[idx]
# be modified:
hidden_states[i][a + 1 : b] = images[idx]
```

**Comment by echo840** [comment]
Hello, we have successfully used the code available at [this link](https://github.com/Yuliang-Liu/Monkey/blob/main/finetune/finetune_textmonkey.sh) for training on an 80g A100 and zero2. The demo code for TextMonkey is as follows: "python demo_textmonkey.py -c model_path."

**Comment by zhangxilin1** [comment]
> > 还没有，我还处于测试阶段。
> 
> Tokenizer 需要添加配置参数
> 
> ```
> tokenizer.IMG_TOKEN_SPAN = 768
> ```
> 
> 并删除“数据”
> 
> ```
> hidden_states[i][a + 1 : b].data = images[idx]
> # be modified:
> hidden_states[i][a + 1 : b] = images[idx]
> ```

这个是在哪个文件下修改 tokenizer.IMG_TOKEN_SPAN = 768
