### ISSUE TITLE
Will Rico data be released?

### ISSUE THREAD

**Issue by YFCYFC** [Yuliang-Liu/Monkey#88]
Hello, great job!
And I am wondering if the Rico data you mentioned in 4.6 App Agent of textmonkey paper will be released.You feature in the paper: We transformed 15k user click data from the Rico [66] dataset and performed downstream fine-tuning using TextMonkey, but the data generation strategies are  not mentioned in the paper at all.Is there any chance that you release the rico data you use or just describe how you generate the image-dialogue pairs?Looking forward to your reply.
Good day.

**Comment by YFCYFC** [comment]
> Here is an example. ` "id": "image path", "conversations": [ { "from": "user", "value": "<img>image_path/img> click on podcasts option. Answer: " }, { "from": "assistant", "value": "<point>(922,580)</point>" } ]` The question is modified from a template, such as "click on XX ”and “select XX", so we can transform the layout of Rico into user-click data.

Yes,understood. But this template is rather simple, and I believe that the multimodal model can not trained to conduct more complex app manipulations. And I am interested in  how to generate the question and the answer just like the conversation in the following image?![image](https://github.com/Yuliang-Liu/Monkey/assets/23159695/616991f4-c1af-403b-a11d-ec6e870dd722)

**Comment by YFCYFC** [comment]
Are GPT or Gemini families employed to generate the questions and the answers?If so, what is the prompt?

**Comment by MelosY** [comment]
Sure, for now, it's a bit simple. You can try using GPT to enhance the prompt later.
