### ISSUE TITLE
How to finetune certain params  via from HF's transformers, a

### ISSUE THREAD

**Issue by JasonLeeFdu** [Yuliang-Liu/Monkey#90]
I have to add one some LoRA layers by hand(without left) to a pre-trained Multi-modal model( only on vision part), to finetune the model for new data. I want Deepspeed to optimize ONLY the parameters from the newly added
 LoRA layer rather than all the parameters. Like this
![image](https://github.com/microsoft/DeepSpeed/assets/44363746/27dc2e18-5d2a-4096-8fc2-75ab242f1f5e)

The platform is hugging face's transformers and Deepspeed.

Therefore I decorate the Trainer from HF's transformers, as below:
![image](https://github.com/microsoft/DeepSpeed/assets/44363746/7ada5cf8-9c91-4023-ac37-b492e368168e)

Unfortunately, it doesn't work, both LoRA and non-LoRa's weights are **not changed** during training. It seems that the optimizer in Deepspeed is not the same as that from Pytorch.

My question is, are there any ways that allow me to **ONLY** finetune certain subnet (LoRA) parameters with Deepspeed+Transformer's Trainer?

**Comment by echo840** [comment]
Hello, in our training of the monkey and monkey-chat models, we only added LoRA to the ViT part, and the LLM was fully trained. You can add similar code to line 368 of  [finetune_multitask.py](https://github.com/Yuliang-Liu/Monkey/blob/main/finetune_multitask.py) to set requires_grad_ to False for parameters you don't need to train, and True for those you do. Please make sure to identify the names of the parameters you don't need to train.

```python
for k,v in model.named_parameters():
    if "lora" in k :#replace "lora" with the names of the parameters you need to train
        v.requires_grad_(True)
```
