### ISSUE TITLE
Get the embeddings of the image.

### ISSUE THREAD

**Issue by xinyanghuang7** [Yuliang-Liu/Monkey#92]
Thank you very much for contributing such an excellent model!

If I want to input a picture and obtain the embedding provided by Monkey-Chat, how should I do it?

Can you help me implement it with a few simple lines of code?

Looking forward to your reply!

Thanks!

**Comment by echo840** [comment]
Hello, maybe you can get the embedding here:
![image](https://github.com/Yuliang-Liu/Monkey/assets/87795401/66e07839-7b65-4c26-b4df-a5fa2824839c)
