### ISSUE TITLE
How to set gpu card for the demo project running

### ISSUE THREAD

**Issue by Mararesliu** [Yuliang-Liu/Monkey#93]
I  use  os.environ["CUDA_VISIBLE_DEVICES"] = "4" or env  to run demo.py, always default use 0, How can i use other gpu card, Is there any i can manully set it?

**Comment by echo840** [comment]
CUDA_VISIBLE_DEVICES=4 python demo_textmonkey.py -c model_path

Maybe you can add "CUDA_VISIBLE_DEVICES=4".

**Comment by echo840** [comment]
![image](https://github.com/Yuliang-Liu/Monkey/assets/87795401/adb06b69-8486-48b9-a652-822f6ee8fa6a)
device_map="cuda:4"
![image](https://github.com/Yuliang-Liu/Monkey/assets/87795401/243c2532-1810-4eb2-9cc8-e6746e2c19b9)
input_ids=input_ids.to("cuda:4"),
attention_mask=attention_mask.to("cuda:4"),


Alternatively, you can modify the code here.

**Comment by Mararesliu** [comment]
The first way not change too.
The second way  demo can no start ,rasie error
![图片](https://github.com/Yuliang-Liu/Monkey/assets/1262534/518607c0-51d4-40c9-be68-325e192b7ba1)
![图片](https://github.com/Yuliang-Liu/Monkey/assets/1262534/7a7449d3-a133-4bd6-8a05-f6d204867c7a)

**Comment by echo840** [comment]
Is your GPU functioning properly? Can you run other models on "cuda:4"? I don't think this is an issue with our code.

**Comment by Mararesliu** [comment]
It works, many thinks.
