### ISSUE TITLE
demo doesn't give OCR with grounding

### ISSUE THREAD

**Issue by jeong-tae** [Yuliang-Liu/Monkey#95]
In the paper, textMonkey in Figure 5, it claims the textMonkey can generate bounding boxes but they always say "use OCR model".
How can I get the OCR visualized result from the model?

**Comment by echo840** [comment]
“OCR with grounding:”   Hello, you can use this prompt.

**Comment by jeong-tae** [comment]
I used this: http://vlrlab-monkey.xyz:7681/
![image](https://github.com/Yuliang-Liu/Monkey/assets/15841995/e9dc2865-6240-4d3a-bae7-42c498cd6e4f)

it doesn't give OCR results. is this intended in the provided demo? should I run `demo_textmonkey.py` myself to get OCR results?

**Comment by echo840** [comment]
I'm  sorry, the demo http://vlrlab-monkey.xyz:7681/ is for Monkey, and for TextMonkey you should run the code （https://github.com/Yuliang-Liu/Monkey/blob/main/demo_textmonkey.py）
