### ISSUE TITLE
eval/eval_doc.sh中运行是的哪个py脚本呢？

### ISSUE THREAD

**Issue by hzy459176895** [Yuliang-Liu/Monkey#98]
![图片](https://github.com/Yuliang-Liu/Monkey/assets/67032748/ff8403e5-57b1-4e5a-b340-c41f9ecbe3ed)

**Comment by echo840** [comment]
![image](https://github.com/Yuliang-Liu/Monkey/assets/87795401/bf64b4e5-4870-450b-8f5f-5fd6679fbce9)
您好，运行的时这个。

**Comment by hzy459176895** [comment]
在后边呀  哈哈  谢谢！
