### ISSUE TITLE
demo_textmonkey.py 模型加载问题

### ISSUE THREAD

**Issue by hzy459176895** [Yuliang-Liu/Monkey#99]
![图片](https://github.com/Yuliang-Liu/Monkey/assets/67032748/50c15f13-cfa8-4b01-9b35-daafd3abd658)
我这个还是报错呢？ 其中的权重路径我是去下载的然后写上的。  里边还有一个18G的bin文件，截图如下：
![图片](https://github.com/Yuliang-Liu/Monkey/assets/67032748/392b528e-27d3-4c41-9c3d-7f30042a4578)

**Comment by hzy459176895** [comment]
有人吗   刚面试不就 issue还比较少  找问题都没答案 - -！

**Comment by MelosY** [comment]
这里是flash attention 的问题,可以尝试一下pip install flash-attn --no-build-isolation。如果只是测试，那么可以在代码中删掉相关内容。
